services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deputy
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - deputy-net

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - miniodata:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - deputy-net

  api:
    build: .
    depends_on:
      - postgres
      - minio
    environment:
      DB_CONNECTION: Host=postgres;Port=5432;Database=deputy;Username=postgres;Password=postgres
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: deputy-files
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN:-}"
      TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID:-}"
      JWT_KEY: "${JWT_KEY:-change_me_in_prod}"
    ports:
      - "5000:80"
    networks:
      - deputy-net

volumes:
  pgdata:
  miniodata:

networks:
  deputy-net:
