version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deputy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d deputy || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - deputy-net

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - miniodata:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - deputy-net

  api:
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    container_name: deputy-api
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      DB_CONNECTION: Host=postgres;Port=5432;Database=deputy;Username=postgres;Password=postgres
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: deputy-files
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN:-}"
      TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID:-}"
      JWT_KEY: "${JWT_KEY:-supersecretjwtkey123!}"
      Jwt__Issuer: deputyapp
      Jwt__Audience: deputyapp
    ports:
        - "5000:80"
    networks:
      - deputy-net

volumes:
  pgdata:
  miniodata:

networks:
  deputy-net:
